### ISSUE TITLE
Incorrect update to price_records.

### ISSUE THREAD

**Issue by harsh-98** [ElrondNetwork/sc-dex-rs#131]
https://github.com/ElrondNetwork/sc-dex-rs/blob/main/dex/elrond_dex_pair/src/oracle.rs#L126-L137

Let say RECORD_BUFFER_MAX_LEN is 10. Then on inserting 10 record the price_records_head is set to 10. And on adding 11th record, new_head will be 1 instead of 0. 
As a result, 11th record will be inserted at index 1.

Fix:
```
 fn commit_current_record(&self, record: &PriceRecord<Self::BigUint>) {
    let len = self.price_records().len();
    if len < RECORD_BUFFER_MAX_LEN {
        self.price_records().push(record);
        self.price_records_head().set(&(len));
    } else {
        let old_head = self.price_records_head().get();
        let new_head = (old_head+1) % RECORD_BUFFER_MAX_LEN;
        self.price_records().set(new_head, record);
        self.price_records_head().set(&new_head);
    }
}

**Comment by VincentHch** [comment]
It's done on purpose, as you can see [here](https://docs.rs/elrond-wasm/0.17.1/elrond_wasm/storage/mappers/struct.VecMapper.html): "Indexes start from 1, instead of 0"
