### ISSUE TITLE
Not receiving MEX from swap

### ISSUE THREAD

**Issue by BeacH105** [ElrondNetwork/sc-dex-rs#133]
I have swap 0.5 EGLD for MEX, but i didn't received the MEX even if EGLD was extracted from exchange
![Missing MEX](https://user-images.githubusercontent.com/90716993/133304872-74e59e29-abb2-4232-b748-b5672c116aea.JPG)

**Comment by BeacH105** [comment]
![image](https://user-images.githubusercontent.com/90716993/133305026-f7e18a9b-8c28-4d96-bbe1-f0ab153190bb.png)

**Comment by andrei-x1** [comment]
This kind of issue should be added in another repo:
https://github.com/ElrondNetwork/battleofyields

**Comment by catalinnnn** [comment]
This is a repo of smart contracts. Please open issues only about smart contracts problems
