### ISSUE TITLE
Missing BUSD from exchange

### ISSUE THREAD

**Issue by BeacH105** [ElrondNetwork/sc-dex-rs#135]
My initial BUSD was diapered from exchange without making any transaction
![Missing BUSD](https://user-images.githubusercontent.com/90716993/133305553-e1cd5882-08a6-4608-a70c-48e688c011cd.JPG)

**Comment by andrei-x1** [comment]
This kind of issue should be added in another repo:
https://github.com/ElrondNetwork/battleofyields

**Comment by catalinnnn** [comment]
This is a repo of smart contracts. Please open issues only about smart contracts problems
