### ISSUE TITLE
error when trying to claim MEX

### ISSUE THREAD

**Issue by BeacH105** [ElrondNetwork/sc-dex-rs#136]
I encounter this error when trying to claim MEX:

![MEX Claim Error](https://user-images.githubusercontent.com/90716993/133306188-ca2f405b-36fb-452f-b1f5-80df7279e0c1.JPG)

**Comment by andrei-x1** [comment]
This kind of issue should be added in another repo:
https://github.com/ElrondNetwork/battleofyields

**Comment by catalinnnn** [comment]
This is a repo of smart contracts. Please open issues only about smart contracts problems
