### ISSUE TITLE
TOCKEN DISAPPEARING

### ISSUE THREAD

**Issue by frick1977** [ElrondNetwork/sc-dex-rs#137]
3.600 BUSD (drop + 2.5 egld swapped) disappeared 19.47 UTC - NOW SOLVED 
![Maiar Chrome](https://user-images.githubusercontent.com/90712024/133306835-1669d63c-623f-4043-b9b5-8fa5890040b0.png)

**Comment by catalinnnn** [comment]
This is a repo of smart contracts. Please open issues only about smart contracts problems
