### ISSUE TITLE
Same tokens swaping twice 

### ISSUE THREAD

**Issue by AbrahamAGV** [ElrondNetwork/sc-dex-rs#138]
While the first swapping of 2500 BUSD to Egld was being processed, I was able to perform a second swapping of the same 2500 BUSD to Egld. Both transactions were occurring at the same time. 

I tried a third time, but the transaction failed. 

(I have a picture of the exact moment it happened)
![image](https://user-images.githubusercontent.com/90717635/133307511-de7e5e2c-7b56-4499-9a33-ced82e763fe2.png)

![image](https://user-images.githubusercontent.com/90717635/133308143-d1d38d07-442f-4519-8184-38e2c50ab44d.png)

**Comment by catalinnnn** [comment]
This is a repo of smart contracts. Please open issues only about smart contracts problems
