### ISSUE TITLE
BUSD to EGLD transaction processed, but continues  showing the "swapping tokens" pop-up window.

### ISSUE THREAD

**Issue by AbrahamAGV** [ElrondNetwork/sc-dex-rs#140]
the BUSD to EGLD transaction had already been processed, but a pop-up window continued to appear in the chrome web browser window as if the transaction was still being processed.

![image](https://user-images.githubusercontent.com/90717635/133308602-48b78c24-97fe-4ac5-a5cb-939824a183a8.png)

**Comment by catalinnnn** [comment]
This is a repo of smart contracts. Please open issues only about smart contracts problems
