### ISSUE TITLE
Cannot reconnect to the testnet even if Maiar says it`s connected

### ISSUE THREAD

**Issue by X-MBN** [ElrondNetwork/sc-dex-rs#141]
![image](https://user-images.githubusercontent.com/90717974/133309461-ff7d0488-68ff-426a-83a1-15a54b0fc586.png)

**Comment by andrei-x1** [comment]
This kind of issue should be added in another repo:
https://github.com/ElrondNetwork/battleofyields

**Comment by catalinnnn** [comment]
This is a repo of smart contracts. Please open issues only about smart contracts problems
