### ISSUE TITLE
MEX funds do not match in the swap and Liquidity tabs.

### ISSUE THREAD

**Issue by AbrahamAGV** [ElrondNetwork/sc-dex-rs#142]
In the swap window it indicates that I have 13150.90 MEX.
![image](https://user-images.githubusercontent.com/90717635/133309978-98bce762-0734-46a7-9e4d-a46c93fe5495.png)

But when I go to add EGLD + MEX liquidity, it tells me that I have 0 MEX.

![image](https://user-images.githubusercontent.com/90717635/133310110-b6d7aeda-507c-41b6-ad84-92ab25e50cda.png)

and sometime appear LKMEX and mex at the same time

![image](https://user-images.githubusercontent.com/90717635/133310662-6b6320e9-1fdb-4448-859c-7f5e7f504e1a.png)

**Comment by catalinnnn** [comment]
This is a repo of smart contracts. Please open issues only about smart contracts problems
