### ISSUE TITLE
Ui: The value of the tokens that are swapped are not correctly changed after max button is press 

### ISSUE THREAD

**Issue by vladMocan** [ElrondNetwork/sc-dex-rs#143]
Steps: 
1.Login into https://testnet.maiar.exchange/swap
2.Navigate to "swap"
3.Select any token and click on max.
4.  Use your keyboard arrows to navigate at the first digit on the value 
5.Try to change the first number of the value.

![Incorect_change](https://user-images.githubusercontent.com/19662439/133310009-36053a5f-cd66-4144-8294-aed45f16a754.gif)

Expected behavior:
The first digit is changed

Actual behavior:
The digit that is enter is enter and the end on the value.

**Comment by andrei-x1** [comment]
This kind of issue should be added in another repo:
https://github.com/ElrondNetwork/battleofyields

**Comment by catalinnnn** [comment]
This is a repo of smart contracts. Please open issues only about smart contracts problems
