### ISSUE TITLE
EGLD disappear after failed transaction

### ISSUE THREAD

**Issue by AbrahamAGV** [ElrondNetwork/sc-dex-rs#145]
After a failed transaction, a pop-up window appears with the eglds that will be returned, then the transaction fails and the eglds disappear.

![image](https://user-images.githubusercontent.com/90717635/133310948-78f6e9eb-f653-4031-9878-df257cbc1ad0.png)

![image](https://user-images.githubusercontent.com/90717635/133310977-097a0cff-1eab-41c4-9949-fb1004c6e3f1.png)

![image](https://user-images.githubusercontent.com/90717635/133311076-130414ad-31bf-475f-8e03-c1c1138826a0.png)

![image](https://user-images.githubusercontent.com/90717635/133311571-5ee13064-3b0c-444b-9e79-0358d2cba5ae.png)

**Comment by catalinnnn** [comment]
This is a repo of smart contracts. Please open issues only about smart contracts problems
