### ISSUE TITLE
Unable to load the account details

### ISSUE THREAD

**Issue by X-MBN** [ElrondNetwork/sc-dex-rs#149]
![image](https://user-images.githubusercontent.com/90717974/133315204-842b6a31-8f7b-4139-a33c-9c5ef5eaa20a.png)

**Comment by andrei-x1** [comment]
This kind of issue should be added in another repo:
https://github.com/ElrondNetwork/battleofyields

**Comment by catalinnnn** [comment]
This is a repo of smart contracts. Please open issues only about smart contracts problems
