### ISSUE TITLE
Swap failed

### ISSUE THREAD

**Issue by BeacH105** [ElrondNetwork/sc-dex-rs#151]
Failed to swap 1 EGLD for MEX

Address: erd1fl2v90drndrq2tmtyfke8vs0ntkdyustrr3h70py7gf9tqwdhemqaa6g3l

Transaction 1 NOK : 6aca2c69ea4b1698183b54b1bdf089a5f3c283331d4450e68656034d0dd82f95
Transactions 2 OK 
![Swap failed 2](https://user-images.githubusercontent.com/90716993/133318036-5163c772-a8d5-4618-a24d-631df19ec603.JPG)
: 8a9c01eb0744ef5a7fba95eb8f36aecdee47965474dd008ed04f054fd54b033a

**Comment by catalinnnn** [comment]
This is a repo of smart contracts. Please open issues only about smart contracts problems
