### ISSUE TITLE
erd1yt8k6jpvjnphty35sz4cedku7uvj2fj9lyap0e5uv9jvar50e5kqd69y7r

### ISSUE THREAD

**Issue by Roberto6161** [ElrondNetwork/sc-dex-rs#153]
After almost an hour with no activities I am still logged in on Maiar Exchange. 
Connection was lost between the mobile app and the web, but I am still able to check everything on Maiar exchange
It not a best practice from GDPR and safety point of view

**Comment by catalinnnn** [comment]
This is a repo of smart contracts. Please open issues only about smart contracts problems
