### ISSUE TITLE
Token not uploaded

### ISSUE THREAD

**Issue by Xavafrica** [ElrondNetwork/sc-dex-rs#157]
Hi, I did many transactions ( 14) but all token are not shown on app. Moreover, every times I reconect i have to start from scratch 
![E6D536F4-4120-4214-A291-7285B570CE4F](https://user-images.githubusercontent.com/90723810/133325557-ce006512-7536-426a-ab54-a2ec90e83057.png)

**Comment by andrei-x1** [comment]
This kind of issue should be added in another repo:
https://github.com/ElrondNetwork/battleofyields

**Comment by catalinnnn** [comment]
This is a repo of smart contracts. Please open issues only about smart contracts problems
