### ISSUE TITLE
erd1lkpalpxllkx8lgcnp5a2x8z5l6u8nvlpmpg0k0mjtj694vnulees2eeszr

### ISSUE THREAD

**Issue by looping18** [ElrondNetwork/sc-dex-rs#160]
Hello,
I found 2 issues :
1- Randomly, when I want to add liquidity to a pool, I do not receive any confirmation to sign using Maiar app. I need to disconnect, then reconnect.

2- Adding liquidity steps : When we have to sign transactions on the Maiar app, it's a bit confusing the description for a regular user.
It's well explained on the website but a bit confusing on the Maiar app
![IMG_0295](https://user-images.githubusercontent.com/48037461/133340551-55f9cbdd-56d7-49c0-b9fd-b8c989ee9a43.jpeg)
![IMG_0296](https://user-images.githubusercontent.com/48037461/133341965-bee3383f-f976-4e99-be45-815623308f6a.PNG)
![IMG_0297](https://user-images.githubusercontent.com/48037461/133341974-23fa3130-4f21-4d69-b89c-28d633e312ca.PNG)
![IMG_0298](https://user-images.githubusercontent.com/48037461/133341982-6f5c4c45-4cb1-4bbe-bcb7-d0496009e01f.PNG)
![IMG_0299](https://user-images.githubusercontent.com/48037461/133341986-e63eb592-106f-4d2f-a7fa-982608fc5302.PNG)

Otherwise the user experience is very impressive for now :)

**Comment by andrei-x1** [comment]
This kind of issue should be added in another repo:
https://github.com/ElrondNetwork/battleofyields

Also, you could split this into 2 issues, if you find this more suitable.

**Comment by catalinnnn** [comment]
This is a repo of smart contracts. Please open issues only about smart contracts problems
