### ISSUE TITLE
Website font hard to read under white background.

### ISSUE THREAD

**Issue by JoeyNapps** [ElrondNetwork/sc-dex-rs#162]
it looks like it's only visible in dark mode. especially "Defi for the next billion and the Learn more button are completely invisible with white back ground

**Comment by andrei-x1** [comment]
This kind of issue should be added in another repo:
https://github.com/ElrondNetwork/battleofyields

Please also include a screenshot (_Attach files by dragging & dropping, selecting or pasting them._)

**Comment by catalinnnn** [comment]
This is a repo of smart contracts. Please open issues only about smart contracts problems
