### ISSUE TITLE
Minimum Slippage tolerance value can be bypass

### ISSUE THREAD

**Issue by N-ozz** [ElrondNetwork/sc-dex-rs#163]
Hello Elrond team,

I have noticed that the minimum slippage tolerance value (0.1%) is force on client-side and can be easily bypass.

<img width="349" alt="Screenshot 2021-09-15 at 12 17 50 PM" src="https://user-images.githubusercontent.com/25240793/133370828-21db02d6-c06b-482d-b13e-8f1996528921.png">

In order to do so it's necessary to modify the value of the tolerance parameter by intercepting the request sent to the graphql endpoint (via a proxy such as BurpSuite). 

See request below :

```POST /graphql HTTP/2
Host: testnet-exchange-graph.elrond.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:92.0) Gecko/20100101 Firefox/92.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: https://testnet.maiar.exchange/
Content-Type: application/json
Authorization: Bearer <redacted>
Origin: https://testnet.maiar.exchange
Content-Length: 796
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
Te: trailers

{"variables":{"sender":"erd1ezlr3wr4vlpd524f9pr2h02wv72rjk8d0rnr2pev7f3llut0x3sslsztz9","pairAddress":"erd1qqqqqqqqqqqqqpgqmffr70826epqhdf2ggsmgxgur77g53hr0n4s38y2qe","tolerance":0.00001,"amountIn":"20000000000000000000","tokenInID":"BUSD-f2c46d","amountOut":"68214590589237583","tokenOutID":"EGLD"},"query":"query ($tolerance: Float!, $amountOut: String!, $tokenOutID: String!, $amountIn: String!, $tokenInID: String!, $pairAddress: String!, $sender: String!) {\n  swapTokensFixedInput(\n    tolerance: $tolerance\n    amountOut: $amountOut\n    tokenOutID: $tokenOutID\n    amountIn: $amountIn\n    tokenInID: $tokenInID\n    pairAddress: $pairAddress\n    sender: $sender\n  ) {\n    value\n    receiver\n    gasPrice\n    gasLimit\n    data\n    chainID\n    version\n    __typename\n  }\n}\n"}

```

In the example above the tolerance parameter have been modify from the minimum `"tolerance":0.001` (0.01%) to `"tolerance":0.00001` (0.001%). The transaction went through normally with the 0.001% slippage https://testnet-explorer.elrond.com/transactions/1ce51f874c40d9b63ebc457381cbe24d37648357740c7ee58db60095ac089e98

Forcing a lower slippage is also possible for e.g 0.00001% or even 0%. Noted that if the tolerance is set too low (0% for example) then the request will be pending and failed for example https://testnet-explorer.elrond.com/transactions/090afa92f3fffe73d06bbd54e17f697fed444ceb7dc7164b61fa1119c2fb6abf

## Impact

I don't think this behavior is expected because it is not possible through the UI to set a lower slippage. That can give a certain advantage to people aware of this bug (as well as bot) over a regular users who are using the UI. Also in another extend this can lead to more pending/fail transactions on the Elrond chain.

Thank you for reading,
Cheers

**Comment by catalinnnn** [comment]
This is a nice find for the UI/Web team but this is a repo of smart contracts. Please open issues only about smart contracts problems.

**Comment by andrei-x1** [comment]
@catalinnnn ,
This is debatable according to this description from here https://github.com/ElrondNetwork/battleofyields :

> Note: security topics should be reported separately at https://github.com/ElrondNetwork/sc-dex-rs

**Comment by catalinnnn** [comment]
What is debatable here? The transaction failed, no? So the contract cannot be tricket. No security issue here. Please describe with technical details any contract problem that you see here.

**Comment by andrei-x1** [comment]
If I read this fragment from the author's post I see that this transaction was successful:

> In the example above the tolerance parameter have been modify from the minimum "tolerance":0.001 (0.01%) to "tolerance":0.00001 (0.001%). The transaction went through normally with the 0.001% slippage https://testnet-explorer.elrond.com/transactions/1ce51f874c40d9b63ebc457381cbe24d37648357740c7ee58db60095ac089e98

He wrote wrong a value there (0.001 is 0.1% and 0.0001 is 0.01%), but he managed to obtain a successful transaction by sending a slippage value that is not allowed by the UI. Right?

**Comment by N-ozz** [comment]
Yes @andrei-x1  that's correct. I was able to made a successful transaction with a lower slippage that what is allow by the UI. For example this transaction have been made with 0.001% https://testnet-explorer.elrond.com/transactions/1ce51f874c40d9b63ebc457381cbe24d37648357740c7ee58db60095ac089e98 (see request above).

Transaction failed happened if the slippage is set way too low (like 0%) - obviously because the price can't be exactly the same while the transaction is proceed.

I would recommend to set a proper minimum value for the slippage parameter on the smart contract itself rather than rely on the front-end.

**Comment by N-ozz** [comment]
@andrei-x1, @catalinnnn let me know if you believe this issue is not related to the smart contract and must be report in another repo. Thank you.
