### ISSUE TITLE
erd1sg7lt7jt6hgqs0l6n6mtdz6mp6grlmdjhssczdwkst8l4dl4gtdqy7rc4f

### ISSUE THREAD

**Issue by Rawslim** [ElrondNetwork/sc-dex-rs#164]
Issue name:
There is no name.

Issue description:
When I try to add liquidity for eGLD-MEX the 3/4 transaction is turning forever and don't want to be validate.

![MAIAR BUG](https://user-images.githubusercontent.com/90776362/133444036-4a2d04aa-e5e8-4309-84d2-5e4af131e26a.PNG)

**Comment by Rawslim** [comment]
![Maiar BUG 2](https://user-images.githubusercontent.com/90776362/133444515-f74ea9ce-ae50-42ca-bed2-3d43fb55f60e.PNG)

**Comment by andrei-x1** [comment]
This should be added in this repo:
https://github.com/ElrondNetwork/battleofyields/issues
