### ISSUE TITLE
erd1f8lreflft8cwvhdg9mu3nsge4mc08p2t48529ttq9nrcw99kez5s6yrv5s

### ISSUE THREAD

**Issue by gelenuts** [ElrondNetwork/sc-dex-rs#167]
Hello, I have not received the 5 EGLDs on my Testnet Maiar exchange.  They are in my testnet wallet but not on the testnet Maiar exchange.  Could you help me sort this out please.  thank you so much

**Comment by andrei-x1** [comment]
This is off-topic here.

Please join https://t.me/MaiarExchange and see the pinned messages.

There is also the following form:
> Please add your issues in this form and we'll do our best to help you asap:
> https://elrondnetwork.typeform.com/to/YlBgE8zH
