### ISSUE TITLE
erd1f8lreflft8cwvhdg9mu3nsge4mc08p2t48529ttq9nrcw99kez5s6yrv5s

### ISSUE THREAD

**Issue by gelenuts** [ElrondNetwork/sc-dex-rs#168]
Hello, I have tested the maiar exchange and it is really good.  I just have a small recommendation for the visual, when we can put liquidity I think that the stack button should be blue and stay black if we do not have liquidity to put.  I don't know if my explanation is quite clear.  I took a photo and circled in red :-)
[the photo link](https://drive.google.com/file/d/1t8faqkgVoQ4-XANDR3N3PKMqd9jbiqQl/view?usp=drivesdk)

**Comment by andrei-x1** [comment]
This repo is for security problems.

Please add your suggestion here:
https://github.com/ElrondNetwork/battleofyields

P.S.: You can also attach files (images) directly from GitHub. You don't need external links (like Google Drive).
