### ISSUE TITLE
Adding LP tokens error

### ISSUE THREAD

**Issue by GeeGold** [ElrondNetwork/sc-dex-rs#170]
Facing numerous errors when trying to convert EGLD and MEX to EGLD-MEX LP tokens while having a positive EGLD-MEX LP token balance. Can only convert to more EGLD-MEX LP tokens once balance has already been staked.

**Comment by andrei-x1** [comment]
This repo is for security problems.

Please add your suggestion here:
https://github.com/ElrondNetwork/battleofyields
