### ISSUE TITLE
BUG ON MEX POOL WHEN REINVEST

### ISSUE THREAD

**Issue by CryptOice2021** [ElrondNetwork/sc-dex-rs#177]
Bonjour,
Dans le pool Mex quand on reinvest la barre de chargement des transactions reste figée à 100%, il faut réactualiser la page pour voir que la transactions est complète avec le cercle vert.

**Comment by catalinnnn** [comment]
This is a repo that contains Smart Contract part of Maiar Exchange. Please open issues only about SC code.
