### ISSUE TITLE
AUTOMATIC LOGOUT

### ISSUE THREAD

**Issue by Vitox2021** [ElrondNetwork/sc-dex-rs#178]
Dear, Elrond team.
I come to report a recurring bug that I sometimes encounter when I connect to the DEX Maiar exchange during my transactions, it tends to disconnect automatically without me doing it myself. I also noticed that the speed of transactions varies between phones, with some it is fast and the latency time is very low while on others it is slow.
Thank you and good luck.

erd1tujdslvucz2jlpccy46lacprmeesgp75d5xx6423x5cuhwjxy0zq9q0x0u

**Comment by catalinnnn** [comment]
This is a repo that contains Smart Contract part of Maiar Exchange. Please open issues only about SC code.
