### ISSUE TITLE
1% fee on withdrawing BUG

### ISSUE THREAD

**Issue by Popugames** [ElrondNetwork/sc-dex-rs#179]
If one user enters the farm and wants to get out of it within 3 epochs, he will receive a 1% penalty from his liquidity. When a user consolidates (reenters farm), compounds or merges positions, the enter moment will be reset to the current epoch. Thus the penalty will apply in the next 3 epochs if the user will exitFarm.

BUG found : 
- on withdraw LP from 2 or 3 farms at the same time, can avoid the penalty of 1% (provided that all transactions are signed before one of them is successful). if a transaction fails you will pay the penalty of 1%
- I noticed this and used it in my favor to win the Battle of Yields

erd1as8u30zlk7n6c3kvcwkegwq5ujmymaadlwyedcj0ywsp785wyt9q36h0n0
Telegram: @popugames

**Comment by catalinnnn** [comment]
The farms have no connections between one another. There is no way they can communicate. Thus I see no way that your described scenario can happen. Do you have any tx hashes that can illustrate the validity of your scenario?

**Comment by Popugames** [comment]
I am waiting for testnet to become functional again, after which i will try to reproduce it.

**Comment by andrei-x1** [comment]
@Popugames ,
Good one! :)

https://github.com/ElrondNetwork/sc-dex-rs/pull/180

**Comment by catalinnnn** [comment]
It has nothing to do with #180

**Comment by Popugames** [comment]
I didn't win the BOY with a bug, it was just an expression to emphasize the
gravity.

mie., 29 sept. 2021, 11:04 catalinnnn ***@***.***> a scris:

**Comment by Popugames** [comment]
- if the timer is global and it resets when you withdraw, the bug is the one mentioned above.
- if it is not global then the bug is that the farms copy the timer from one another.

**Comment by Popugames** [comment]
I'm still working on reproducing all the scenarios. 
This can take up to 24 hours.

**Comment by catalinnnn** [comment]
That's fine. We're curious to see the results

**Comment by Popugames** [comment]
the wrong information in the UI makes my testing difficult. - which of the 2 is wrong?
![20210929_120124](https://user-images.githubusercontent.com/33068457/135248013-3369111b-b2a5-41ff-a20e-8fd9ee21bbea.jpg)

**Comment by Popugames** [comment]
the wrong information in the UI makes my testing difficult.
 - which of the 2 is wrong?
![20210929_120124](https://user-images.githubusercontent.com/33068457/135248188-46549ecc-393e-42c4-9e7a-231cd3a389fe.jpg)

**Comment by cyparu** [comment]
> the wrong information in the UI makes my testing difficult.
> 
> * which of the 2 is wrong?
>   ![20210929_120124](https://user-images.githubusercontent.com/33068457/135248188-46549ecc-393e-42c4-9e7a-231cd3a389fe.jpg)
This issue was already summited here: https://github.com/ElrondNetwork/battleofyields/issues/992

**Comment by catalinnnn** [comment]
Do you have any updates here @Pogugames?

**Comment by Popugames** [comment]
Looks like it's a UI bug. I can't figure out if it's a problem because it gives me a different result every time. it seems that the farms share the timer with each other.
- the timer do not work properly
- image 01 (reinvest MEX farm) look on EGLD-BUSD timer
- image 02 (15 min later) look on EGLD-BUSD timer
- 
 if you don't understand anything I don't understand either

![20210930_193639](https://user-images.githubusercontent.com/33068457/135504126-b4f6026c-82b9-417d-8aee-8740fd46cfca.jpg)
![20210930_193712](https://user-images.githubusercontent.com/33068457/135504151-47f10308-ec59-467a-b156-84a8b5cc1f7e.jpg)

**Comment by catalinnnn** [comment]
Cool, the UI team is already working on fixing this timers on the Frontend. Is there anything more? Or we can close this issue?

**Comment by Popugames** [comment]
You can close the issue. Thank you
