### ISSUE TITLE
Proposal: Possibility to split LP-tokens when withdrawing them from a farm, make it possible to only withdraw the unlockable portion

### ISSUE THREAD

**Issue by janniksam** [ElrondNetwork/sc-dex-rs#229]
Maybe my thinking is bad or I am missing something, but I really miss a feature right now:

**Imagine the following scenario:**
- I have a few LP tokens in the EGLD/LKMEX pool.
- 10 % of these LP tokens contain unlockable LKMEX right now
- 90 % are not unlockable right now

**The goal:**
I would like to unlock the 10% of the unlockable LKMEX. So I will need to remove exactly those LP pairs, that include those 10%, that can be unlocked. Then I can remove the LP pairs withdrawn and remove it.

**The problem:**
The DEX is currently not capable of spitting LKMEX / LP-tokens into multiple types and give back only the unlockable portion. This results in us having to remove 100% of the liquidity, every time we want to unlock a portion of the LKMEX.

In a few countries, removing LP-tokens is a taxable action, So in these countries we don't want to have to remove more liquidity than actually necessary.

--------

**My (updated) idea (no idea if this is possible):**

Lets imagine you have 10 LKMEX#001 staked/in liquidity, which contains 10% unlockable LKMEX right now, and 90% unlockable in the future:

1. When unstaking liquidity, the smart contract could burn all LP Tokens and mint two new types, One LP token type includes a new type of LKMEX#002 and another one LKMEX#003.
    - LKMEX#002 will contain the unlockable 10% of LKMEX.
    - LKMEX#003 will contain the rest
    - User will get 10% LP Tokens with LKMEX#002 and 90% with LKMEX#003.

2. User only has to remove the 10% LKMEX#002 and does only create potentially taxable events for these 10%.

**Comment by BogdanCalacean** [comment]
Thumbs up for this! Definetely something that might be useful. @janniksam one thing I noticed was that for the withdrawn LP tokens, the percentages remain similar.

If you remove 5% then
10% of this 5% will be unlockable 
90% of this 5% will be locked

Same happens if you remove 20%
10% of this 20% will be unlockable 
90% of this 20% will be locked and so on

**Comment by janniksam** [comment]
Unfortunately this does in fact mean, I would have to withdrawal every single LP, remove every single LP and then unlocking, readding and restaking. 

Instead of just picking the right ones and just withdrawing and removing them.

**Comment by janniksam** [comment]
I thought about it a bit more, maybe my proposal is technically impossible at the moment.

Partially it would still help us, because we get the unlockable first, but think about this:

In a scenario, where I have one LKMEX-#1151 pile. All #1151 contain 20 % unlockable now, 80 % unlockable in the future.
How can you split them up from a technical standpoint? You cant just split them up. The 20:80 ratio would still exist, its still a #1151-type.

You'd have to create two new LKMEX-types, e.g. #1152 and #1153 - one containing the 20% unlockable, and the other everything else.

**Comment by janniksam** [comment]
Has anyone ever read this proposal/problem and did think about a solution?

**Comment by sasurobert** [comment]
The architecture does not allow this. as farms do not know about what kind of LKMEX do you have.
