### ISSUE TITLE
Harvesting on MEX farm and harvesting immediately after on MEX-EGLD LP does not create 2 separate transactions

### ISSUE THREAD

**Issue by BogdanCalacean** [ElrondNetwork/sc-dex-rs#338]
Today tried to harvest from the MEX farm and from the MEX-EGLD LP

Clicked harvest first on MEX farm, confirmed transaction using the Web Wallet then clicked harvest on the MEX-EGLD LP and confirmed using the Web Wallet. After that there seem to have been 2 transactions created but with the same Tx. ID as it can be seen in the screenshot below (in the explorer there is only 1 transaction appearing - bd8640341a61408127198b6d0c12efbd9423a1d24ec0ff73c957fcb2b3d79916) 

![image (3)](https://user-images.githubusercontent.com/16613446/158565553-103d2d39-6083-425e-bf8a-a9dc6d68a15a.png)

Now the second transaction never finishes and the Earned MEX in the MEX - EGLD is still claimable. 

Of course, this worked once I clicked harvest once again but just something that might be updated.

**Comment by sasurobert** [comment]
Resolved with next release.
