### ISSUE TITLE
[FEAT] Add button to open wallet address in elrond explorer

### ISSUE THREAD

**Issue by janniksam** [ElrondNetwork/sc-dex-rs#398]
This does not exactly belong into the smart contract repository, but it's the next best thing that relates to the DEX...

I'd love to have a second button (next to the "copy address" button), that opens the wallet @ https://explorer.elrond.com/

![image](https://user-images.githubusercontent.com/15337798/166102179-2d6b79d1-7aad-4a90-a1ce-f9d2cf144d98.png)

**Comment by sasurobert** [comment]
Transmitted to relevant team.
