### ISSUE TITLE
Problem on redeeming WEGLD from ASHEGLDD

### ISSUE THREAD

**Issue by RaduGabor** [ElrondNetwork/sc-dex-rs#682]
Hi! 

I tried to redeem WEGLD from ASH price discovery using Xexchange interface and I have a transaction error.
Here is the transaction: https://explorer.elrond.com/transactions/032685066ac6f82d90fa43722c85d239bce6265c81d7be886c9eb0955c90803d

The error is: **Argument decode error (sync result): input too short**

I think the function is: https://github.com/ElrondNetwork/sc-dex-rs/blob/main/dex/price-discovery/src/lib.rs/#L225

Thanks.

**Comment by ovidiuolteanu** [comment]
Hello,

Thank you for your report. 
We are aware of this situation and we're currently working on it.
We will perform a contract upgrade to cover this specific case soon.
